[build]
  command = "python downloadLLM.py && pip install langchain_community && python ingest.py && chainlit run model.py"
  functions = "functions"
  publish = "dist"

[functions]
  directory = "functions"
